openapi: 3.0.1

info:
  title: Portfolio Budget
  description: Simple backend API to manage portfolio budget using an envelope budgeting
    method
  version: 1.0.0


servers:
- url: http://localhost:4001/


paths:
  /api/v1/envelopes:
    get:
      tags:
      - Envelopes
      summary: Get all envelopes
      responses:
        200:
          description: Returns a list of all envelopes
          content: {}
    post:
      tags:
      - Envelopes
      summary: Make a new envelop
      requestBody:
        description: Write a new envelope
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                title:
                  type: string
                budget:
                  type: integer
      responses:
        201:
          description: A new envelop successufully made
          content: {}
        500:
          description: Internal server error
          content: {}
  /api/v1/envelopes/{id}:
    get:
      tags:
      - Envelopes
      summary: Get a specific envelop by ID
      parameters:
      - name: id
        in: path
        description: Enter a number to fetch an envelop
        required: true
        schema:
          type: integer
      responses:
        200:
          description: Returns an envelope along with its data
          content: {}
        404:
          description: User not found
          content: {}
        500:
          description: Internal server error
          content: {}

components: {}
